### ISSUE TITLE
comments + votes with time stamp

### ISSUE THREAD

**Issue by PaulieScanlon** [sungwoncho/node-producthunt#3]
Would it be possible a bit more information about the comments and votes

Comments: return date posted and name of user who posted

Votes: return date vote was posted and name of user who posted

**Comment by sungwoncho** [comment]
See the official doc: https://api.producthunt.com/v1/docs/comments_and_comment_threads/comments_index_fetch_all_threads_of_a_post_(nested_and_sorted).

I can see that the payload includes `created_at`.

This package cannot support anything other than what the official API supports because it's just a wrapper.
